version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5100:5100"
    env_file:
      - ./backend/.env
    networks:
      - app-net

  frontend:
    build: ./fronted/todo-frontend
    ports:
      - "3100:3100"  # El frontend sirve en el puerto 3100
    networks:
      - app-net
    depends_on:
      - backend

networks:
  app-net:
    driver: bridge
